import { useState, useEffect } from 'react'
import { faker } from '@faker-js/faker'
import './SidePanel.css'

export const SidePanel = () => {
  const [clickedElementId, setClickedElementId] = useState(null)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  function sendFill() {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      chrome.tabs.sendMessage(tabs[0].id, {
        type: 'fillLastInput',
        elementId: clickedElementId,
        value: faker.lorem.word(),
      })
    })
  }

  useEffect(() => {
    // Listen for messages from the content script
    const handleMessage = (message, sender, sendResponse) => {
      if (message.type === 'updateClickedElement') {
        setClickedElementId(message.value)
      }
    }

    chrome.runtime.onMessage.addListener(handleMessage)

    // Cleanup listener on component unmount
    return () => {
      chrome.runtime.onMessage.removeListener(handleMessage)
    }
  }, [])

  return (
    <main>
      <h3>Fake data...</h3>
      <h4>Input: {clickedElementId ?? '-'}</h4>

      <button onClick={sendFill}>Fill with random data...</button>

      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default SidePanel
